# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true


minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.0.6+1.21.1
maven_group=dev.sterner
archives_base_name=guardvillagers

# Dependencies
fabric_version=0.116.0+1.21.1

midnightlib_version=1.5.7-fabric
spell_engine_version=1.6.10+1.21.1
spell_power_version=1.3.0+1.21.1
